# Generated by Django 4.2.3 on 2023-07-06 19:37

import django.core.validators
from django.db import migrations, models
import notas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura_semestre_nota',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='asignatura_semestre_nota',
            name='nota',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[notas.validators.validate_nota]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ci',
            field=models.CharField(max_length=50, unique=True, validators=[notas.validators.validate_ci]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator('Email no valido')]),
        ),
    ]
